#!/usr/bin/env python3
"""
Hub-board layout diagram (control/harness/hub_board.svg).

Revision 2026-10-08.1: the hub board is the UART junction only. It holds the
one UART resistor R1 and the bus node where RX2 and the four driver PDN_UART
leads meet. No 12 V, no fuse, no Phoenix header (those went when the key
driver moved to the RAMPS E0 socket).

Not a PCB layout — a placement guide so Paul can see what sits where. The
links shown are nets; on a perfboard they are point-to-point wires underneath.

    python3 control/harness/hub_board.py
"""
import os

REV = open(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "REVISION")).read().strip()

SCALE = 8.0
MARGIN = 48
BW_MM, BH_MM = 40, 30
BX, BY = MARGIN, 150
BW, BH = BW_MM * SCALE, BH_MM * SCALE
RIGHT = BX + BW + 60
W = RIGHT + 430
H = BY + BH + 150

C = {
    'UART': '#27ae60', 'board': '#eef2f3', 'edge': '#7f8c8d',
    'ink': '#2c3e50', 'pale': '#95a5a6', 'res': '#bdc3c7',
}


def main():
    s = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W:.0f}" height="{H:.0f}" '
         f'viewBox="0 0 {W:.0f} {H:.0f}" font-family="Helvetica,Arial,sans-serif">',
         f'<rect width="{W:.0f}" height="{H:.0f}" fill="white"/>']

    def txt(x, y, t, size=12, bold=False, col=None, anc='start'):
        w = ' font-weight="bold"' if bold else ''
        s.append(f'<text x="{x:.0f}" y="{y:.0f}" font-size="{size}"{w} '
                 f'fill="{col or C["ink"]}" text-anchor="{anc}">{t}</text>')

    def pad(x, y, r=6, col=None):
        s.append(f'<circle cx="{x:.0f}" cy="{y:.0f}" r="{r}" fill="{col or C["UART"]}" stroke="{C["ink"]}" stroke-width="1.2"/>')

    def wire(x0, y0, x1, y1):
        s.append(f'<path d="M{x0:.0f},{y0:.0f} L{x1:.0f},{y1:.0f}" fill="none" '
                 f'stroke="{C["UART"]}" stroke-width="2.6" stroke-linecap="round"/>')

    # ---- title ----
    txt(MARGIN, 42, 'Hub board — the UART junction', 24, True)
    txt(W - MARGIN, 30, f'Revision {REV}', 11, col=C['pale'], anc='end')
    txt(MARGIN, 68, "Revision 2026-10-08.1: with all four drivers on the RAMPS, the hub is just R1 and the UART bus node.", 12.5)
    txt(MARGIN, 86, "No 12 V, no fuse, no Phoenix header. A small perfboard beside the Mega. Keep R1 right at the TX2 pin.", 12.5)
    txt(MARGIN, 104, "Nets shown; on a perfboard they are point-to-point wires underneath.", 12.5, col=C['pale'])

    # ---- board ----
    s.append(f'<rect x="{BX:.0f}" y="{BY:.0f}" width="{BW:.0f}" height="{BH:.0f}" rx="8" '
             f'fill="{C["board"]}" stroke="{C["edge"]}" stroke-width="2"/>')

    # pin column on the left of the board
    px = BX + 40
    pins = [('TX2', 'to AUX-4 18 / D16'), ('RX2', 'to AUX-4 17 / D17'),
            ('BUS X', 'X socket MS3 pin'), ('BUS Y', 'Y socket MS3 pin'),
            ('BUS Z', 'Z socket MS3 pin'), ('BUS E0', 'E0 socket MS3 pin (key)')]
    def py(k): return BY + 28 + k * 32
    for k, (nm, note) in enumerate(pins):
        pad(px, py(k), 6)
        txt(px - 12, py(k) + 4, nm, 11, True, anc='end')

    # R1 between the TX2 pin and the bus node
    rx0, rx1 = px + 150, px + 210
    ry = py(0)
    s.append(f'<rect x="{rx0:.0f}" y="{ry-9:.0f}" width="{rx1-rx0:.0f}" height="18" rx="3" fill="{C["res"]}" stroke="{C["ink"]}" stroke-width="1.3"/>')
    txt((rx0+rx1)/2, ry+4, 'R1 1k', 11, True, anc='middle')
    wire(px, ry, rx0, ry)
    # bus node: vertical line to the right of R1, joining rows 1..5 and R1 out
    xn = px + 250
    wire(rx1, ry, xn, ry)
    for k in range(1, 6):
        wire(px, py(k), xn, py(k))
        pad(xn, py(k), 4)
    s.append(f'<line x1="{xn:.0f}" y1="{py(0):.0f}" x2="{xn:.0f}" y2="{py(5):.0f}" stroke="{C["UART"]}" stroke-width="2.6"/>')
    pad(xn, py(0), 4)
    txt(xn + 10, py(2) + 4, 'bus node', 11, True, C['UART'])
    txt(xn + 10, py(3) + 4, 'RX2 + R1 (from TX2) + all 4 PDN_UART', 9.5, col=C['pale'])

    # ---- net list on the right ----
    lx = RIGHT + 80
    txt(lx, 150, 'What lands where', 15, True)
    rows = [
        ('TX2', 'from AUX-4 pin 18 (D16) → R1 → bus node'),
        ('RX2', 'from AUX-4 pin 17 (D17) → bus node'),
        ('BUS X / Y / Z / E0', 'the four MS3 jumper pins (signal side) → bus node'),
    ]
    y = 180
    for a, b in rows:
        pad(lx + 7, y - 4, 6)
        txt(lx + 22, y, a, 12, True)
        txt(lx + 22, y + 15, b, 10)
        y += 42
    txt(lx, y + 4, 'Bus = the datasheet single-wire UART (TMC2209 Fig. 4.1):', 11)
    txt(lx, y + 20, 'TX2 → 1 kΩ → bus; RX2 and every PDN_UART on the bus.', 10)
    txt(lx, y + 40, 'Use 2.54 mm male pins for the jumper ends; RAMPS side uses', 10)
    txt(lx, y + 54, 'F–F jumpers (~10 cm). That is the whole hub board.', 10)

    txt(MARGIN, H - 14, 'Generated by control/harness/hub_board.py from control/wiring.md section 5.', 9.5, col=C['pale'])

    s.append('</svg>')
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'hub_board.svg')
    open(out, 'w').write('\n'.join(s))
    print('wrote', out)


if __name__ == '__main__':
    main()
